= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Das Produkt (die Software) wird als Verkaufssoftware ausschließlich firmenintern (lokal auf den Computern laufend) in der Vinothek „La Bouteille“ benutzt werden. Dabei wird ein Mitarbeiter, die Software bedienend, den Kunden durch den Kaufprozess begleiten. Dadurch soll der Verkaufsprozess sowohl für die Kunden als auch für die Mitarbeiter übersichtlicher und effizienter gestaltet werden. Ermöglicht wird dies durch die zentrale Verwaltung verschiedener Prozesse (die im Zusammenhang mit dem Verkauf stehen) innerhalb der Software (Lagerverwaltung, Bestellungsübersicht, Warenkatalog, Kundeninformationen).

Die Software wird über einen Browser bedient, soll jedoch nicht für Benutzer außerhalb des lokalen Netzwerkes zugänglich sein. Trotzdem sollte sichergestellt werden, dass die Software visuell korrekt auf gängigen Browsern (Google Chrome (Version 86.0.4240.198), Mozilla Firefox (Version 82.0.3)) läuft.

Primär wird die Software von den Mitarbeitern der „La Bouteille“ bedient, welche nicht zwingend mit dem technischen Hintergrund der Software vertraut sind. Deshalb sollte die gesamte Benutzeroberfläche übersichtlich und möglichst intuitiv gestaltet werden, und die Software an sich keine technische Wartung benötigen.

Die Daten sollen dauerhaft in einer lokalen Datenbank gespeichert werden und durch die Software erreichbar sein.

== Aufbau der Testbezeichner
Nach welchem Schema sind die Tests benannt?


*U - Unit Test, I - Integrationstest*

*U-1, U-2, I-1*

== Test Gegenstände
|===
|Controller a|
CustomerController, UserController, CatalogController, IndexController, OrderController
|Entitäten a|
Customer, User, Wine
|Repostitory a|
CustomerRepository, UserRepository, WineCatalog
|DataInitializer a|
CustomerDataInitializer, UserDataInitializer, WineDataInitializer
|Management a|
CustomerManager, UserManager, CatalogManager
|Sonstige a|
CustomerRegistrationForm, UserRegistrationForm, NewProductForm	
|===
== Zu testende Funktionalitäten

* CustomerController 
* UserController
* CatalogController
* IndexController
* OrderController
* WineCatalog
* CustomerManager
* UserManager 
* CatalogManager
* WineCatalog

== Nicht zu testende Funktionalitäten

* CustomerDataInitializer 
* UserDataInitializer
* WineDataInitializer
* CustomerRepository
* UserRepository
* CustomerRegistrationForm
* UserRegistrationForm
* NewProductForm
* Customer
* User
* Wine
* Bibliotheken von Drittanbietern (eigene Tests beschränken sich auf Schnittstelle, bzw. Zusammenspiel).

== Herangehensweise

* Klassen werden mit JUnit getestet
* Integrationstest nach Bottom-Up Prinzip

== Umgebungsvoraussetzungen
=== Hardware-Vorgaben

Eine Liste mit benötigter Hardware, um mit der Software interagieren zu können.

* Computer
* Tastatur
* Maus

=== Software-Vorgaben
Eine Liste mit benötigter Software, um mit der Software interagieren zu können.

Diese oder eine neuere Version von Java wird benötigt:

* Java 11


== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|AT0010  |UC0101     |Benutzer nicht eingeloggt        |Nutzername, Passwort       |Erfolg(Startseite) bei Fehler bleibt man auf der login Seite
|AT0011|UC0101| Benutzer ist angemeldet |Benutzer drückt auf ausloggen|Startseite (ausgeloggt)
|AT0020|UC0402|Admin ist angemeldet|Name, Vorname, Username, Passwort|Neuer Mitarbeiter Acc wurde erstellt
|AT0030|UC0102|Mitarbeiter nimmt Kunden auf der noch nicht registriert ist|Vorname, Nachname, Email, Adresse|Kundendaten werden angelegt
|AT0040|UC0103|Mitarbeiter verwendet das System|Mitarbeiter drückt auf Katalogverwaltung|Katalog seite wid aufgerufen
|AT0050|UC0104|Auf der Katalog Seite sein |Auf den gewünschten Wein klicken|Details des Weines
|AT0060|UC0201|Auf der Katalog Seite|Den gwünschten Wein suchen und dann die Anzahl der Weine anklicken|Die gewünschte Anazhl wurde dem Warenkorb hinzugefügt
|AT0070|UC0203|Im System Angemeldet sein|Auf Warenkorb klicken|Warenkorb Ansicht
|AT0071|UC0202|Auf der Warenkorb Seite|auf bearbeiten klicken und die Anzahl verändern|Die Anzahl wurde verändert
|AT0072|UC0204|Auf der Warenkorb Seite, mindestens 1 Produkt im Warenkorb|"Kaufen" Knopf drücken|Rechnung wird erstellt und der Kunde hat den gewünschten Wein gekauft
|AT0080|UC0301|Mitarbeiter ist angemeldet|Klickt auf Kunden|Die Kunden Seite wird aufgerufen
|AT0090|UC0302|Admin verwendet das System|Auf Inventar klicken|Es werden alle Items des Inventares angezeigt
|AT0100|UC0303|Mitarbeiter verwendet das System|klickt auf Rechnungen|Es werden alle Rechnungen aufgelistet
|AT0110|UC0402|Admin verwendet das System und klickt auf der Mitarbeiter Seite auf neuen Mitarbeiter hinzufügen| Vorname, Nachname, Username, Passwort |Ein Mitarbeiter Acc wurde erstellt
|AT0120|UC0403|Admin verwendet das System und ist auf der Inventar Seite|Auf den Knopf Nachbestellen klicken und die gewünschte Anzahl nachbestellen |Produkt wird nachbestellt
|AT0130|UC0404|Admin verwendet das System|auf Mitarbeiter klicken|Alle Mitarbeiter werden angezeigt
|===
