= Test-Plan

Dieser Testplan stellt eine vereinfachte Version der IEEE 829-1998 Vorlage dar.

== Einführung
Das Produkt (die Software) wird als Verkaufssoftware ausschließlich firmenintern (lokal auf den Computern laufend) in der Vinothek „La Bouteille“ benutzt werden. Dabei wird ein Mitarbeiter, die Software bedienend, den Kunden durch den Kaufprozess begleiten. Dadurch soll der Verkaufsprozess sowohl für die Kunden als auch für die Mitarbeiter übersichtlicher und effizienter gestaltet werden. Ermöglicht wird dies durch die zentrale Verwaltung verschiedener Prozesse (die im Zusammenhang mit dem Verkauf stehen) innerhalb der Software (Lagerverwaltung, Bestellungsübersicht, Warenkatalog, Kundeninformationen).

Die Software wird über einen Browser bedient, soll jedoch nicht für Benutzer außerhalb des lokalen Netzwerkes zugänglich sein. Trotzdem sollte sichergestellt werden, dass die Software visuell korrekt auf gängigen Browsern (Google Chrome (Version 86.0.4240.198), Mozilla Firefox (Version 82.0.3)) läuft.

Primär wird die Software von den Mitarbeitern der „La Bouteille“ bedient, welche nicht zwingend mit dem technischen Hintergrund der Software vertraut sind. Deshalb sollte die gesamte Benutzeroberfläche übersichtlich und möglichst intuitiv gestaltet werden, und die Software an sich keine technische Wartung benötigen.

Die Daten sollen dauerhaft in einer lokalen Datenbank gespeichert werden und durch die Software erreichbar sein.

== Aufbau der Testbezeichner
Nach welchem Schema sind die Tests benannt?


*U - Unit Test, I - Integrationstest*

*U-1, U-2, I-1*

== Test Gegenstände
|===
|Controller a|
CustomerController
UserController
CatalogController
IndexController
|Entitäten a|
Customer
User
Wine
|Repostitory a|
CustomerRepository
UserRepository
WineCatalog

|Daten Erstbesitzer a|
CustomerDataInitializer
UserDataInitializer
WineDataInitializer
|Management a|
CustomerManager
UserManager
CatalogManager
|Sonstige a|
CustomerRegistrationForm
UserRegistrationForm
NewProductForm	
|===
== Zu testende Funktionalitäten

== Nicht zu testende Funktionalitäten
z.B. Bibliotheken von Drittanbietern (eigene Tests beschränken sich auf Schnittstelle, bzw. Zusammenspiel).

== Herangehensweise

*Klassen werden mit JUnit getestet.*
*Integrationstest nach Bottom-Up Prinzip*

== Umgebungsvoraussetzungen
=== 2.1 Hardware-Vorgaben

Eine Liste mit benötigter Hardware, um mit der Software interagieren zu können.

* Computer
* Tastatur
* Maus

=== 2.2 Software-Vorgaben
Eine Liste mit benötigter Software, um mit der Software interagieren zu können.

Diese oder eine neuere Version von Java wird benötigt:

* Java 11


== Testfälle und Verantwortlichkeit
Jede testbezogene Aufgabe muss einem Ansprechpartner zugeordnet werden.

// See http://asciidoctor.org/docs/user-manual/#tables
[options="headers"]
|===
|ID |Anwendungsfall |Vorbedingungen |Eingabe |Ausgabe
|…  |…              |…              |…       |…
|===
