= Zeiterfassung für Gruppe 37

Notieren Sie die Zeit in Minuten für jeden Entwickler und – getrennt davon – für Team-Treffen pro Woche (Wochengranularität).
Die individuell erfasste Zeit beinhaltet auch das Lesen von Dokumentationen, Besprechungen mit Teamkollegen und sonstige auf das Praktikum bezogene Aufgaben, jedoch *nicht* das Team-Treffen (= letzte Spalte).

// See http://asciidoctor.org/docs/user-manual/#tables
[option="headers"]
|===
|Woche |David |Deokgeun |Henrik |Lavon |Noah |Tom |Meeting
|1  |960   |600    |720    |1140    |780   |240    |90+30+30+90+60    
|2  |1920   |1200    |1020    |540    |1170    |350    |90    
|3  |780   |900    |720    |1440    |1320    |985    |90    
|4  |900   |1800    |1260   |1200    |1000    |210    |90   
|5  |1020   |720    |1140    |1500    |900    |960   |90 
|6  |720   |360    |540    |1000    |1100    |330    |90    
|7  |360   |700    |780   |700    |1000    |1080    |90   
|8  |720   |…    |600  |…      |660   |315    |90   
|9  |360   |…    |540    |…    |600    |…    |90    
|10  |…   |…    |600    |…    |700    |…    |90    
|11  |…   |…    |…    |…    |…    |…    |90    
|12  |…   |…    |…    |…    |…    |…    |…    
|===

Bitte tragen Sie am Ende des Praktikums noch folgende weitere Werte ein:
Summe der Arbeitsstunden pro Student:

SUMME(SPALTE(DevX))

Arbeitsstunden pro Woche pro Student:

SUMME(SPALTE(DevX)) / 12

Durchschnittliche Arbeitzeit aller Studenten pro Woche:

(SUMME(SPALTE(Dev1)) + SUMME(SPALTE(Dev2)) + SUMME(SPALTE(Dev3)) + SUMME(SPALTE(Dev4)) + SUMME(SPALTE(Dev5)) +SUMME(SPALTE(Dev6))) / 6
